name: CI

on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup-build
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Run build
        run: ./gradlew build
